server:
  port: 8081
  servlet:
    context-path: /provider
spring:
  application:
    name: service-provider
  datasource:
    url: jdbc:mysql:///leyou?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: wizard
    password: 123
mybatis:
  type-aliases-package: com.wizard.service.model
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
